// <auto-generated />
using BlockbusterResurrected.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlockbusterResurrected.Migrations
{
    [DbContext(typeof(BlockbusterResurrectedContext))]
    [Migration("20210111194002_fixInitial")]
    partial class fixInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlockbusterResurrected.Models.Console", b =>
                {
                    b.Property<int>("ConsoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConsoleName");

                    b.HasKey("ConsoleId");

                    b.ToTable("Consoles");
                });

            modelBuilder.Entity("BlockbusterResurrected.Models.ConsoleGame", b =>
                {
                    b.Property<int>("ConsoleGameId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ConsoleId");

                    b.Property<int>("GameId");

                    b.HasKey("ConsoleGameId");

                    b.HasIndex("ConsoleId");

                    b.HasIndex("GameId");

                    b.ToTable("ConsoleGame");
                });

            modelBuilder.Entity("BlockbusterResurrected.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GameTitle");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BlockbusterResurrected.Models.ConsoleGame", b =>
                {
                    b.HasOne("BlockbusterResurrected.Models.Console", "Console")
                        .WithMany("Games")
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BlockbusterResurrected.Models.Game", "Game")
                        .WithMany("Consoles")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
